var annotated_dup =
[
    [ "BatteryMonitor", "class_battery_monitor.html", "class_battery_monitor" ],
    [ "BluetoothBatteryCurrentCallbacks", "class_bluetooth_battery_current_callbacks.html", "class_bluetooth_battery_current_callbacks" ],
    [ "BluetoothBatteryPercentCallbacks", "class_bluetooth_battery_percent_callbacks.html", "class_bluetooth_battery_percent_callbacks" ],
    [ "BluetoothBatteryVoltageCallbacks", "class_bluetooth_battery_voltage_callbacks.html", "class_bluetooth_battery_voltage_callbacks" ],
    [ "BluetoothDeviceService", "class_bluetooth_device_service.html", "class_bluetooth_device_service" ],
    [ "BluetoothPowerService", "class_bluetooth_power_service.html", "class_bluetooth_power_service" ],
    [ "BluetoothServer", "class_bluetooth_server.html", "class_bluetooth_server" ],
    [ "BluetoothServerCallbacks", "class_bluetooth_server_callbacks.html", "class_bluetooth_server_callbacks" ],
    [ "BluetoothSolarCurrentCallbacks", "class_bluetooth_solar_current_callbacks.html", "class_bluetooth_solar_current_callbacks" ],
    [ "BluetoothSolarVoltageCallbacks", "class_bluetooth_solar_voltage_callbacks.html", "class_bluetooth_solar_voltage_callbacks" ],
    [ "BluetoothUartService", "class_bluetooth_uart_service.html", "class_bluetooth_uart_service" ],
    [ "BluetoothUartServiceCallbacks", "class_bluetooth_uart_service_callbacks.html", "class_bluetooth_uart_service_callbacks" ],
    [ "CAT_M1", "class_c_a_t___m1.html", "class_c_a_t___m1" ],
    [ "CLI", "class_c_l_i.html", "class_c_l_i" ],
    [ "CLICatM1", "class_c_l_i_cat_m1.html", "class_c_l_i_cat_m1" ],
    [ "CLIConfig", "class_c_l_i_config.html", "class_c_l_i_config" ],
    [ "CLIConfigIntervals", "class_c_l_i_config_intervals.html", "class_c_l_i_config_intervals" ],
    [ "CLIMQTT", "class_c_l_i_m_q_t_t.html", "class_c_l_i_m_q_t_t" ],
    [ "CLIPower", "class_c_l_i_power.html", "class_c_l_i_power" ],
    [ "CLISdi12", "class_c_l_i_sdi12.html", "class_c_l_i_sdi12" ],
    [ "DeviceConfig", "class_device_config.html", "class_device_config" ],
    [ "SDCardInterface", "class_s_d_card_interface.html", "class_s_d_card_interface" ],
    [ "SolarMonitor", "class_solar_monitor.html", "class_solar_monitor" ],
    [ "TCA9534", "class_t_c_a9534.html", "class_t_c_a9534" ]
];