M48
; DRILL file {KiCad (6.0.11-0)} date Wednesday, 19 April 2023 at 02:37:29 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-19T14:37:29+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.556
%
G90
G05
T1
X36.888Y-97.843
T2
X45.092Y-132.845
T0
M30
