M48
; DRILL file {KiCad (6.0.7-1)-1} date Tuesday, 17 January 2023 at 11:35:27 am
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-17T11:35:27+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.556
%
G90
G05
T1
X36.888Y-97.843
T2
X45.092Y-132.845
T0
M30
